# Generated by Django 2.2.4 on 2019-12-06 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhymesapp', '0006_remove_account_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rhyme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('link', models.URLField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='account',
            name='street_address',
        ),
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.CharField(default=3083932939, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='zipcode',
            field=models.CharField(default=40404, max_length=5),
            preserve_default=False,
        ),
    ]
