# Generated by Django 2.2.4 on 2019-12-10 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhymesapp', '0010_auto_20191209_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rhyme',
            name='premium',
            field=models.BooleanField(default=True),
        ),
    ]
