# Generated by Django 2.2.4 on 2019-12-11 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rhymesapp', '0012_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
